### ISSUE TITLE
Is this package still maintained?

### ISSUE THREAD

**Issue by mmollick** [DripEmail/drip-php#11]
I see there hasn't been any recent activity for this repository. Just a few stale PRs and a couple of issues that haven't been responded to. However, the Ruby and NodeJS wrappers have been fairly active within the last few weeks.

On that note, it seems this package is a little out of date with modern PHP practices/standards. It's not even available via Composer/Packagist. Are there any plans on modernizing the code base and doing a proper release for Composer?

**Comment by tnorthcutt** [comment]
Hiya @mmollick! I recently (well, back in October, I guess) started helping out with maintaining this package. I use it in a project and wanted to help make sure it stays current.

While I can't dedicate a ton of time to it, I'd love to see improvements, and would be happy to review and merge PRs as appropriate. If you'd like to contribute, I'd suggest opening an issue or PR prior to writing any code, explaining what you'd like to change, and we can take it from there.

Thanks!

**Comment by mmollick** [comment]
Thanks for the reply @tnorthcutt. That's good to hear that the repo hasn't been abandoned.

I only bring this up because I'm a little reluctant to rely on this package in its current state. Between the single monolith class, legacy PHP support, lack of unit tests, and lack of composer support I've got my concerns.

I'd really love a chance to help modernize and refactor the wrapper but to do so is going to require some changes to the scope of the project. Here's what I'm proposing for bringing this wrapper into 2018:

- Move the current code to a "1.0" or "legacy" branch
- Drop support for EOL'd PHP versions (support >=5.6)
- Refactor the single class into properly namespaced classes (PSR-4)
- Add unit testing and linting to project
- Hook it up to .travis.ci (or another CI) as well as CodeClimate
- Add package to Packagist and follow semantic versioning for future changes

I know there's been some reluctance to make significant changes to the master branch but to breath some new life into this package we'll have to be able to make changes to it. I understand the concern for those who are referencing the master branch directly in their applications, but this isn't a practice we should concern ourselves with. Any issues that arise from doing this lie solely with the package's user and not the package's maintainer. It shouldn't stifle the ability to make improvements to the package.

If we absolutely can't make modifications to the master branch, I would suggest that Drip (@djreimer) depreciate this repository and create a new one that allows for a modern PHP package to be created. There's been a lot of changes in PHP since this package has been updated.

Cheers!

**Comment by tnorthcutt** [comment]
@mmollick I like the overall aim of this proposal!

There are a few aspects (CI, CodeClimate, Packagist) that are beyond what I'm willing or able to engage with, but I certainly see the merits, and perhaps the Drip team and/or @djreimer can help us with those.

Regardless, the other items certainly seem sensible from my perspective. @djreimer can we get a blessing on moving forward with this?

**Comment by djreimer** [comment]
Yep, I agree that this API wrapper is in much need of modernization. Our engineering team does not have a ton of bandwidth to focus on the long tail of API wrappers at the moment. I would love to see @mmollick's proposal come to life and it think it makes most sense for this to become a community-supported wrapper for the time being.

I would probably recommend cutting a fresh repo that adhere's to the PHP community packaging standards and harvesting from this repo as it makes sense to do so. Once a stable alternative is ready to go, I'd be happy to link out to your project as the de-facto wrapper.

**Comment by tnorthcutt** [comment]
@djreimer just curious, is your suggestion to start a new repo because you're concerned about breaking changes/deprecation, or b/c you want to make it clear that Drip isn't the maintainer?

**Comment by djreimer** [comment]
I think it will help on both of those fronts, honestly.

**Comment by mmollick** [comment]
Thanks for the input. I'll go ahead and create a fresh repository then. Should have a first release available next week.

**Comment by djreimer** [comment]
Excellent, thanks for taking this on!

**Comment by tnorthcutt** [comment]
Rad. @mmollick I'd definitely love to be added. Thanks!
