### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by thomask** [DripEmail/drip-php#12]
Hey guys!

I just [added this package to Packagist](https://packagist.org/packages/dripemail/drip-php). Would you mind tagging a release here, to indicate a stable version? This is needed for people to install the package.

Thanks!

**Comment by will-in-wi** [comment]
I'm working on a cleanup of the codebase right now, and was planning on pushing to Packagist once I got the 1.0 release out. In the interim, I've tagged `v0.0.1` as the version that's been out for a while and `v0.0.2` as the latest master with Composer.

Could you transfer ownership of https://packagist.org/packages/dripemail/drip-php to the dripemail user (if that's normally how this is done)? Thanks!

**Comment by mmollick** [comment]
@will-in-wi a few months ago I wrote a modern PHP library to replace this one (see #11). I'd be happy to submit a PR with the changes if you'd like. The library is available here: https://github.com/mmollick/drip-php It's currently using my namespace so as not to conflict with any official development done here.

**Comment by will-in-wi** [comment]
Version 1.0.0 is out, with initial Composer and PSR-4 support.

@mmollick That looks great! I'd be happy to work with you to try and bring a lot of that back into this client.

**Comment by thomask** [comment]
Will try and look in to this today!

**Comment by thomask** [comment]
Hey there, I couldn't find a way to transfer ownership, so I went ahead an deleted the package. You should be able to re-register it. Could you please do that ASAP, otherwise builds might start failing.

Thanks!

**Comment by will-in-wi** [comment]
Thanks! I've re-registered the package: https://packagist.org/packages/dripemail/drip-php

I've also set up the github webhooks, so it should update automagically.
