### ISSUE TITLE
PHP package on Packagist

### ISSUE THREAD

**Issue by grogy** [DripEmail/drip-php#14]
Is possible register package in Packagist?

For now on Packagist are only unofficial packages - https://packagist.org/?query=drip%20php

When you want I can help you. Simle manual how add package:

- Go to https://packagist.org/packages/submit
- Paste link of this repository and click Check
- After check phase is complete, click on Submit

That's it, the library is available on Packagist

**Comment by will-in-wi** [comment]
We're tracking this work on the (probably misnamed at this point) https://github.com/DripEmail/drip-php/issues/12

**Comment by grogy** [comment]
Nice, thank you
