### ISSUE TITLE
Make properties, method protected rather than private

### ISSUE THREAD

**Issue by tdtm** [DripEmail/drip-php#16]
We need to add methods to class `\Drip\Client` so we were looking at extending it with our custom class, adding the functionality that we need (and use that in our uses rather than the base class).

But many properties and attributes in `Drip\Client` are `private`; I don't see why they couldn't be `protected` instead? That would make it possible for others (like us) to extend it.

**Comment by tdtm** [comment]
There are no contribution guidelines in the repo, but if you need I can do a PR although for something as simple I'd think it's more efficient if you guys do it 😬

**Comment by will-in-wi** [comment]
That makes sense to me, feel free to make such a PR! I'm guessing that those of us who write Ruby most of the time forgot that Ruby private is closer to PHP protected.

**Comment by will-in-wi** [comment]
This just got released in 1.1.0.

**Comment by tdtm** [comment]
That was efficient! Thanks, much appreciated.
