### ISSUE TITLE
Add fetch_subscriber_campaigns

### ISSUE THREAD

**Issue by tdtm** [DripEmail/drip-php#18]
`fetch_subscriber_campaigns` is available in the API but not in the PHP wrapper.

We've added this one, we were going to subclass it (hence #16 ) but upon internal discussion, it's not specific to us and everyone can benefit so we'll PR it in here. 

PR to follow when I can get a minute :)

**Comment by will-in-wi** [comment]
Thanks! Looking forward to it.

**Comment by tdtm** [comment]
I totally forgot about this 😬 Thanks to teammate @hannesvdvreken for sorting it out!

**Comment by will-in-wi** [comment]
I just released v1.3.0 with this change. Thanks!

**Comment by tdtm** [comment]
Thanks @hannesvdvreken & @will-in-wi !
