### ISSUE TITLE
Manual installation (Without composer)

### ISSUE THREAD

**Issue by caraffa** [DripEmail/drip-php#19]
For those who don't have access to a command line (like most of us who have hosted web plans) installation via Composer is out of reach.
This library is useless for me.

**Comment by will-in-wi** [comment]
A common approach in this case is to run composer locally and commit the entire `vendor/` directory to your repository, which is then deployed to the server along with the rest of the application.

Does this work?

**Comment by caraffa** [comment]
Well, yes, it works. Sorry for my not really sweet wording, but it's the first time I face a situation like this (but not the only one?)
May I suggest to write this in the README?
Anyway, this version of the library looks better the the previous one.

Thanks

P.S.: By the way. This version of the library breaks for sure any previously dependent software.
May be it should be stated more clearly in the README

**Comment by will-in-wi** [comment]
I added a note about breaking backwards compatibility to the changelog, thanks for the suggestion!
