### ISSUE TITLE
Is there a reason the Bearer authorization header is not used?

### ISSUE THREAD

**Issue by jtsternberg** [DripEmail/drip-php#25]
We have a working Drip integration, but were looking to switch to the official library. But [the way authentication happens](https://github.com/DripEmail/drip-php/blob/b1ddc423ef18495c236e1aad6f9309d2fcbe12dd/src/Client.php#L337-L352) does not work for us (we get authentication errors). However if switch to using the Bearer authorization token header, things work as expected. E.g.

```php
... 
$client = new \GuzzleHttp\Client();

$req_params = [
    'base_uri' => $this->api_end_point,
    'handler' => $stack,
    'timeout' => $this->timeout,
    'connect_timeout' => $this->connect_timeout,
    'http_errors' => false,
    'headers'  => array(
        'User-Agent' => $this->user_agent(),
        'Accept' => 'application/json, text/javascript, */*; q=0.01',
        'Content-Type' => 'application/vnd.api+json',
    	'Authorization' => 'Bearer ' . $this->api_token,
    ),
];
... switch case statement ...

$res = $client->request($req_method, $url, $req_params); 
```

**Comment by jtsternberg** [comment]
Anyone home?

**Comment by will-in-wi** [comment]
Hey, sorry, this got overlooked. We haven't been spending much time on this client in a while, but I'll throw a ticket in the queue for this.

**Comment by tiannaavery** [comment]
Thanks for your patience on this one! Version 1.4.0 has a new client definition that supports Bearer authentication.
