### ISSUE TITLE
Issue with CURLOPT_FOLLOWLOCATION

### ISSUE THREAD

**Issue by toptensoftware** [DripEmail/drip-php#3]
I'm using this library on a nearlyfreespeech.net server and it's complaining about the CURLOPT_FOLLOWLOCATION not being allowed with an open base dir.  (Basically this: http://stackoverflow.com/questions/2511410/curl-follow-location-error).  

NearlyFreeSpeech don't give a "full server" so to speak and their systems are kinda locked down which is where I presume is the cause of the error.  On a virtual server box at home it works fine.

I've disabled the option on my server by commenting out that line and the error's gone and it seems to be working but I'm just using one api method (create_or_update_subscriber).

Wondering if there's a more subtle problem and whether this flag is actually necessary.

**Comment by will-in-wi** [comment]
Version 1 pulled in Guzzle to try and clean this stuff up, so this shouldn't be an issue anymore. Feel free to reopen if that's not the case.
