### ISSUE TITLE
Working with Composer on php 7.4.x

### ISSUE THREAD

**Issue by benklocek** [DripEmail/drip-php#39]
I'm struggling to use the library with php 7.4.x, as composer seems to think it needs 8.2 to run.

Is there a way to force it to use 7.4 for this composer.json, so that the Autoload script will run on my server with 7.4.29?

**Comment by alpharder** [comment]
Just use `--ignore-platform-reqs` flag when running composer

**Comment by natebrunette** [comment]
@benklocek could you provide the error you're seeing? This library should be compatible with php 8.

**Comment by benklocek** [comment]
> Just use `--ignore-platform-reqs` flag when running composer

I'll give that a try @alpharder. Thanks for the suggestion. I'm new to composer.

@natebrunette My client is not ready to upgrade his server to php8 yet, so I'm trying to get it working on php7.4.x.

**Comment by benklocek** [comment]
UPDATE: Yay! That did the trick. Thank you @alpharder!
