### ISSUE TITLE
uniqueness_error when calling create_or_update_subscriber for existing subscriber

### ISSUE THREAD

**Issue by thomask** [DripEmail/drip-php#7]
As the method name suggests, it should be able to update an existing subscriber using this method. However, the API returns a `uniqueness_error` with message `User is already being used` when I try to update a subscriber. Any clues?

**Comment by thomask** [comment]
Guys, earlier your support department told me to ask my questions here, but I am not getting an answer here either. What should I do to actually get support?

**Comment by samudary** [comment]
Hey @thomask I just responded to you via email since this may require the exchange of some private data in your Drip account.
